services:
  fineapp-a:
    image: fineapp
    environment:
      AppName: A
    build:
      context: .
      dockerfile: FineApp/Dockerfile
    ports:
      - 8080:8080
  fineapp-b:
    image: fineapp
    environment:
      AppName: B
    build:
      context: .
      dockerfile: FineApp/Dockerfile
    ports:
      - 8081:8080
  fineapp-c:
    image: fineapp
    environment:
      AppName: C
    build:
      context: .
      dockerfile: FineApp/Dockerfile
    ports:
      - 8082:8080
