services:
  fineapp-a:
    image: fineapp
    environment:
      AppName: A
    build:
      context: .
      dockerfile: FineApp/Dockerfile
  fineapp-b:
    image: fineapp
    environment:
      AppName: B
    build:
      context: .
      dockerfile: FineApp/Dockerfile
  fineapp-c:
    image: fineapp
    environment:
      AppName: C
    build:
      context: .
      dockerfile: FineApp/Dockerfile
  cache:
    image: redis:6.2-alpine
    restart: always
  proxy:
    image: proxy
    environment:
      ReverseProxy__Clusters__clusterA__Destinations__destination1__Address: "http://fineapp-a:8080/"
      ReverseProxy__Clusters__clusterA__Destinations__destination2__Address: "http://fineapp-b:8080/"
      ReverseProxy__Clusters__clusterA__Destinations__destination3__Address: "http://fineapp-c:8080/"
      ConnectionStrings__redis: "cache:6379"
    build:
      context: .
      dockerfile: FineYarp/Dockerfile
    depends_on:
      - fineapp-a
      - fineapp-b
      - fineapp-c
    ports:
      - 8080:8080
  fineweb:
    image: fineweb
    environment:
      Services: "http://fineapp-a:8080/, http://fineapp-b:8080/, http://fineapp-c:8080/"
      YarpUrl: "http://proxy:8080"
    build:
      context: .
      dockerfile: FineWeb/Dockerfile
    ports:
      - 8079:8080
