services:
  fineapp-a:
    image: fineapp
    environment:
      AppName: A
    build:
      context: .
      dockerfile: FineApp/Dockerfile
    ports:
      - 8081:8080
  fineapp-b:
    image: fineapp
    environment:
      AppName: B
    build:
      context: .
      dockerfile: FineApp/Dockerfile
    ports:
      - 8082:8080
  fineapp-c:
    image: fineapp
    environment:
      AppName: C
    build:
      context: .
      dockerfile: FineApp/Dockerfile
    ports:
      - 8083:8080
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
  proxy:
    image: proxy
    environment:
      ReverseProxy__Clusters__clusterA__Destinations__destination1__Address: "http://fineapp-a:8080/"
      ReverseProxy__Clusters__clusterA__Destinations__destination2__Address: "http://fineapp-b:8080/"
      ReverseProxy__Clusters__clusterA__Destinations__destination3__Address: "http://fineapp-c:8080/"
      ConnectionStrings__redis: "cache:6379"
    build:
      context: .
      dockerfile: FineYarp/Dockerfile
    ports:
      - 8080:8080
